config/routes.rb
Betastore::Application.routes.draw do

	namespace :admin do
		resources :products
		get '/orders' => 'orders#index', as: 'orders_path'
		root :to => 'products#index'
	end

	get '/categories/:category_id/products' => 'products#index', as: 'category_products'

	resources :products
	
  	resources :subscriptions

  	get '/checkout' => 'orders#new', as: 'checkout'
  	post '/checkout' => 'orders#create'

  	get '/cart' => 'cart_items#index', as: 'cart_items'
	post '/products/:product_id/cart_items' => 'cart_items#create', as: 'add_to_cart'

	get '/forgot_password' => 'password_resets#new', as: 'forgot_password'
	post '/forgot_password' => 'password_resets#create'

	get '/reset_password/:id/:token' => 'password_resets#edit', as: 'reset_password'
	post '/reset_password/:id/:token' => 'password_resets#update'

	get '/sign_up' => 'customers#new', as: 'sign_up'
	post '/sign_up' => 'customers#create'
	# get '/sign_up' => 'customers#edit', as: 'update'
	# post '/sign_up' => 'customers#update'

	get '/log_in'  => 'log_ins#new', as: 'log_in'
	post '/log_in'  => 'log_ins#create'
	post '/log_out' => 'log_ins#destroy', as: 'log_out'

	root :to => 'products#index'

end

app/models/cart_item.rb
class CartItem
	attr_accessor :product, :quantity

	def initialize(product, quantity)
		@product = product
		@quantity = quantity
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :product_categorizations
  has_many :products, :through => :product_categorizations
end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders
  	has_many :line_items, :through => :orders
  	has_many :products, :through => :line_items
  	has_many :password_resets

  	validates_presence_of :name, :email, :password

  	has_secure_password

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product

  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  
  before_validation :set_price
  
  def set_price
    self.price = product.price
  end
  
  def total_price
    quantity * product.price
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :customer
    belongs_to :credit_card
    has_many :line_items
    accepts_nested_attributes_for :line_items, :credit_card

    before_save :set_total_amount

  def self.recent
    where("placed_at > ?", 7.days.ago)
  end

  def self.by(customer)
    where(customer_id: customer.id)
  end

  def total_price
    line_items.inject(0) do |sum, li|
      li.total_price + sum
    end
  end

  def set_total_amount
    self.total_amount = total_price
  end
end

app/models/password_reset.rb
class PasswordReset < ActiveRecord::Base
  belongs_to :customer

  before_validation :generate_token
  validates_presence_of :customer_id, :token

  def generate_token
    self.token ||= SecureRandom.hex(16)
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders, :through => :line_items
  has_many :product_categorizations
  has_many :categories, :through => :product_categorizations

  validates :name, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  def self.in_category(category_id)
    includes(:product_categorizations)
      .where('product_categorizations.category_id' => category_id)
  end

end

app/models/product_categorization.rb
class ProductCategorization < ActiveRecord::Base
  belongs_to :category
  belongs_to :product
end

app/models/refund.rb
class Refund < ActiveRecord::Base
	belongs_to :order
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	# Prevent CSRF attacks by raising an exception.
  	# For APIs, you may want to use :null_session instead.
  	# protect_from_forgery with: :exception
	
	before_filter :require_log_in

  protected

 	def require_log_in
   		redirect_to '/log_in' unless logged_in?
  	end

  helper_method :logged_in?, :current_customer
  def logged_in?
   		cookies.signed[:customer_id].present?
 	end

  def current_customer
      @customer ||= Customer.find(cookies.signed[:customer_id])
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
	skip_before_filter :require_log_in

	def index
		@cart_items = Hash(session[:cart]).map do |pid, qty|
			CartItem.new(Product.find(pid), qty)
		end
		render layout: !request.xhr?
	end

	def create
		session[:cart] ||= Hash.new(0)
		session[:cart][params[:product_id]] += 1
		respond_to do |format|
			format.html do
				redirect_to products_path, notice: "Product #{params[:product_id]} was added to your cart"
			end
			format.json do
				render json: { 
					cart: session[:cart], 
					item_count: session[:cart].values.sum
				}
			end
		end
	end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  skip_before_filter :require_log_in, only: [:new, :create]

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      cookies.signed[:customer_id] = @customer.id
      redirect_to products_path
    else
      render 'new'
    end
  end

  # def edit
  # end

  # def update
  # end

  private
  def customer_params
    params.require(:customer).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/log_ins_controller.rb
class LogInsController < ApplicationController
  
  skip_before_filter :require_log_in 
  
  def create
    customer = Customer.find_by(email: params[:email])
    if customer && customer.authenticate(params[:password])
      cookies.signed[:customer_id] = customer.id
      redirect_to products_path
    else
      redirect_to log_in_path, alert: 'Log In Failed'
    end
  end

  def destroy
    cookies.delete(:customer_id)
    redirect_to products_path
  end

end


# Look up the Customer using the email and then if we find one 
# and if it successfully authenticates using the password that was supplied 
# then we set the ID of the Customer in a cookie

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_filter :require_log_in, only: [:new, :create]

  def new
    @order = Order.new
    @order.build_credit_card
    Hash(session[:cart]).each do |pid, qty|
      @order.line_items.build(
        product_id: pid,
        quantity: qty)
    end
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to root_path, notice: 'Your order has been placed'
    else
      flash.now[:alert] = @order.errors.full_messages.join(', ')
      logger.error "errors: #{@order.errors.full_messages.join(', ')}"
      render 'new'
    end
  end

  protected
  def order_params
    params.require(:order).permit(
      line_items_attributes: [:product_id, :quantity],
      credit_card_attributes: [:cardholder_name, :card_number, :expiration_month, :expiration_year])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	skip_before_filter :require_log_in

	def index
		@products_page = true
	    @categories = Category.all

	    scope = Product

	    if params[:min_price].present?
	      scope = scope.where('price >= ?', params[:min_price])
	    end

	    if params[:max_price].present?
	      scope = scope.where('price <= ?', params[:min_price])
	    end

	    if params[:category_id].present?
	      scope = scope.in_category(params[:category_id])
	    end

	    @products = scope.page(params[:page]).per(12)

	    respond_to do |format|
	      format.html
	      format.rss
	    end
	end

	# def create
	# 	@product = Product.new(product_params)

	# 	respond_to do |format|
	# 		if @product.save
	# 			format.html do
	# 				redirect_to product_path(@product), notice: 'Product was saved'
	# 			end
	# 			format.json do
	# 				render json: @product
	# 			end
	# 		else
	# 			format.html do
	# 				render 'edit'
	# 			end
	# 			format.json do
	# 				render json: { errors: @product.errors}, status: 422
	# 			end
	# 		end
	# 	end
	# end

	def show
		@product = Product.find(params[:id])
	end

	# private
	# def product_params
	# 	params.require(:product).permit(:name, :price)
	# end

end

app/controllers/refunds_controller.rb
class RefundsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

	def cart_item_count
		if session[:cart]
			session[:cart].values.sum
		else
			0
		end
	end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/_footer.html.erb
<hr />
© Betamore <%= Time.current.year %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default">
  <ul class="nav navbar-nav">
    <li><%= link_to "Products", products_path, method: 'get' %></li>
    <% if logged_in? %>
    	<li><%= link_to "Log Out", log_out_path, method: 'post' %></li>
    <% else %>
    	<li><%= link_to "Sign Up", sign_up_path, method: 'get' %></li>
    	<li><%= link_to "Log In", log_in_path, method: 'get' %></li>
    <% end %>
    <li><%= link_to cart_items_path, :class => 'cart' do %>
    		Cart (<span id="cart_item_count"><%= cart_item_count %></span>)
      <% end %>
    </li>
  </ul>
  
  <% if @products_page %>
    <ul class="nav navbar-nav navbar-right">
      <li><p class="navbar-text">Sort by:</p></li>

      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Price <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% [4.99, 9.99, 14.99].each do |price| %>
              <li><%= link_to "#{price} and up", min_price: price %></li>
            <% end %>
          </ul>
        </li>

      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Category <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% @categories.each do |category| %>
              <li><%= link_to category.name, category_products_path(category) %></li>
            <% end %>
          </ul>
      </li>    
    </ul>
  <% else %>
  <% end %>
</div>



<!-- add if statment for page, set instance variable before filter on controller pages to make class='active' for <li> dynamic -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Betastore</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div style="margin: 0 auto; text-align: center">
    <%= image_tag "logo.jpg", width: 600 %>
    <%= render 'layouts/header' %>
      <% if flash[:alert] %>
        <p class="alert alert-warning"><%= flash[:alert] %></p>
      <% end %>

      <% if flash[:notice] %>
        <p class="alert alert-success"><%= flash[:notice] %></p>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>